# Created by trellis-cli vcanary
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  rootstest.de:
    site_hosts:
    - canonical: rootstest.de
      redirects:
      - www.rootstest.de
    local_path: ../site
    branch: main
    repo: git@github.com:sjsiegel001/rootstest-trellis.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    object_cache:
      enabled: true
      provider: redis
    xmlrpc:
      enabled: false
    env:
      umami_website_id: "fc80b222-893b-44a1-9b79-bde2029a7ea0"
