# Created by trellis-cli vcanary
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  rootstest.de:
    site_hosts:
    - canonical: rootstest.de
      redirects:
      - www.rootstest.de
    local_path: ../site
    branch: main
    repo: git@github.com:sjsiegel001/rootstest-trellis.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
